[package]
name = "adam_fov_rs"
description = "A rust implementation of Adam Milazzo's FOV algorithm http://www.adammil.net/blog/v125_Roguelike_Vision_Algorithms.html#mine"
version = "0.1.3"
edition = "2021"
authors = ["sark", "Adam Milazzo"]
homepage = "https://github.com/sarkahn/adam_fov_rs"
repository = "https://github.com/sarkahn/adam_fov_rs"
license = "MIT"
readme = "README.md"
keywords = ["fov", "field-of-view", "roguelike", "2d"]

[dependencies]
glam = { version = "0.20.0" }

[dev-dependencies]
bevy = {version = "0.6", default-features = false, features = ["png", "bevy_winit", "render"]}
bevy_ascii_terminal = { path="../bevy_ascii_terminal", version= "0.9.0" }
bevy_tiled_camera = "0.3.0"
rand = "0.8.4"